### ISSUE TITLE
Tests errors in windows

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/sugoi-api#73]
When using windows with JDK 11.0.9 and building sugoi-api with `mvn package`, process exit with errors : 

```
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Users\USER\AppData\Local\Programs\jdk-11.0.9+11\bin\java -javaagent:C:\\Users\\USER\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.4\\org.jacoco.agent-0.8.4-runtime.jar=destfile=C:\\Users\\USER\\Documents\\dev\\sugoi-api\\sugoi-api-ldap-store-provider\\target\\jacoco.exec -jar C:\Users\USER\temp\surefire345198285959551297\surefirebooter11487559930431689607.jar C:\Users\USER\temp\surefire345198285959551297 2021-01-14T09-54-02_245-jvmRun1 surefire16528952380935067697tmp surefire_148524147527092363468tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] fr.insee.sugoi.ldap.LdapWriterStoreTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:690)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:447)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:423)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by fjr3o6** [comment]
Le problème ne se pose pas avec eclipse et le maven intégré.
